-- 1. Create the movies table if it doesn't exist
create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add columns if they don't exist (Idempotent)
do $$
begin
  -- Text fields (Basic Info)
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'title') then
    alter table public.movies add column title text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'description') then
    alter table public.movies add column description text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'category') then
    alter table public.movies add column category text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'frontImage') then
    alter table public.movies add column "frontImage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'backImage') then
    alter table public.movies add column "backImage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'certification') then
    alter table public.movies add column certification text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'backImage') then
    alter table public.movies add column "backImage" text;
  end if;
  -- Phase 7: Carousel specific image
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'carouselImage') then
    alter table public.movies add column "carouselImage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'watchLink') then
    alter table public.movies add column "watchLink" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'language') then
    alter table public.movies add column language text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'country') then
    alter table public.movies add column country text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'releaseDate') then
    alter table public.movies add column "releaseDate" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'director') then
    alter table public.movies add column director text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'updated_at') then
    alter table public.movies add column updated_at timestamp with time zone default timezone('utc'::text, now()) not null;
  end if;
  -- Duration
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'duration') then
    alter table public.movies add column duration text;
  end if;

  -- Phase 2 New Columns: Type & Status
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'type') then
       alter table public.movies add column type text default 'movie'; -- 'movie' or 'series'
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'status') then
       alter table public.movies add column status text default 'published'; -- 'published' or 'draft'
  end if;

  -- Numeric/Boolean fields
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'year') then
    alter table public.movies add column year integer;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'rating') then
    alter table public.movies add column rating numeric;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'top10') then
    alter table public.movies add column "top10" boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'isNewRelease') then
    alter table public.movies add column "isNewRelease" boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'isPopular') then
    alter table public.movies add column "isPopular" boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'featured') then
    alter table public.movies add column featured boolean default false;
  end if;

  -- JSONB fields
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'cast') then
    alter table public.movies add column "cast" jsonb;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'writers') then
    alter table public.movies add column writers jsonb;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'awards') then
    alter table public.movies add column awards jsonb;
  end if;
  -- Phase 2 New Columns: Series Support
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'seasons') then
    alter table public.movies add column seasons jsonb; -- Detailed season/episode data
  end if;
  
  -- Phase 6: Top 10 Ordering
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'top10_order') then
    alter table public.movies add column "top10_order" integer default 0;
  end if;
end $$;

-- 3. Create Homepage Config Table (Phase 2)
create table if not exists public.homepage_config (
    id bigint generated by default as identity primary key,
    key text unique not null,
    value jsonb not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS and Policies
alter table public.movies enable row level security;
alter table public.homepage_config enable row level security;

-- Policy for Public Read Access (Movies)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'movies' and policyname = 'Allow public read access') then
    create policy "Allow public read access" on public.movies for select to anon using (true);
  end if;
end $$;

-- Policy for Public Read Access (Config)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'homepage_config' and policyname = 'Allow public read access config') then
    create policy "Allow public read access config" on public.homepage_config for select to anon using (true);
  end if;
end $$;

-- Policy for Insert/Update (Dev Mode - should restrict to authenticated users in prod)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'movies' and policyname = 'Allow anon insert/update') then
    create policy "Allow anon insert/update" on public.movies for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'movies' and policyname = 'Allow authenticated full access') then
    create policy "Allow authenticated full access" on public.movies for all to authenticated using (true) with check (true);
  end if;

    if not exists (select 1 from pg_policies where tablename = 'homepage_config' and policyname = 'Allow anon insert/update config') then
    create policy "Allow anon insert/update config" on public.homepage_config for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'homepage_config' and policyname = 'Allow authenticated full access config') then
    create policy "Allow authenticated full access config" on public.homepage_config for all to authenticated using (true) with check (true);
  end if;
end $$;
