
import { useState } from 'react';
import { supabase } from '../../supabaseClient';
import { FaUpload, FaDatabase, FaCheck, FaExclamationTriangle } from 'react-icons/fa';

const DataImport = () => {
  const [uploadStatus, setUploadStatus] = useState('');
  const [loading, setLoading] = useState(false);
  const [jsonFile, setJsonFile] = useState(null);
  const [showSql, setShowSql] = useState(false);

  const sqlScript = `
-- 1. Create the movies table if it doesn't exist
create table if not exists public.movies (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Add columns if they don't exist (Idempotent)
do $$
begin
  -- Text fields (Basic Info)
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'title') then
    alter table public.movies add column title text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'description') then
    alter table public.movies add column description text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'category') then
    alter table public.movies add column category text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'frontImage') then
    alter table public.movies add column "frontImage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'backImage') then
    alter table public.movies add column "backImage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'certification') then
    alter table public.movies add column certification text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'backImage') then
    alter table public.movies add column "backImage" text;
  end if;
  -- Phase 7: Carousel specific image
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'carouselImage') then
    alter table public.movies add column "carouselImage" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'watchLink') then
    alter table public.movies add column "watchLink" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'language') then
    alter table public.movies add column language text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'country') then
    alter table public.movies add column country text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'releaseDate') then
    alter table public.movies add column "releaseDate" text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'director') then
    alter table public.movies add column director text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'updated_at') then
    alter table public.movies add column updated_at timestamp with time zone default timezone('utc'::text, now()) not null;
  end if;

  -- Phase 2 New Columns: Type & Status
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'type') then
       alter table public.movies add column type text default 'movie'; -- 'movie' or 'series'
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'status') then
       alter table public.movies add column status text default 'published'; -- 'published' or 'draft'
  end if;

  -- Numeric/Boolean fields
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'year') then
    alter table public.movies add column year integer;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'rating') then
    alter table public.movies add column rating numeric;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'top10') then
    alter table public.movies add column "top10" boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'isNewRelease') then
    alter table public.movies add column "isNewRelease" boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'isPopular') then
    alter table public.movies add column "isPopular" boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'featured') then
    alter table public.movies add column featured boolean default false;
  end if;

  -- JSONB fields
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'cast') then
    alter table public.movies add column "cast" jsonb;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'writers') then
    alter table public.movies add column writers jsonb;
  end if;
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'awards') then
    alter table public.movies add column awards jsonb;
  end if;
  -- Phase 2 New Columns: Series Support
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'seasons') then
    alter table public.movies add column seasons jsonb; -- Detailed season/episode data
  end if;
  
  -- Phase 6: Top 10 Ordering
  if not exists (select 1 from information_schema.columns where table_name = 'movies' and column_name = 'top10_order') then
    alter table public.movies add column "top10_order" integer default 0;
  end if;
end $$;

-- 3. Create Homepage Config Table (Phase 2)
create table if not exists public.homepage_config (
    id bigint generated by default as identity primary key,
    key text unique not null,
    value jsonb not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Enable RLS and Policies
alter table public.movies enable row level security;
alter table public.homepage_config enable row level security;

-- Policy for Public Read Access (Movies)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'movies' and policyname = 'Allow public read access') then
    create policy "Allow public read access" on public.movies for select to anon using (true);
  end if;
end $$;

-- Policy for Public Read Access (Config)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'homepage_config' and policyname = 'Allow public read access config') then
    create policy "Allow public read access config" on public.homepage_config for select to anon using (true);
  end if;
end $$;

-- Policy for Insert/Update (Dev Mode - should restrict to authenticated users in prod)
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'movies' and policyname = 'Allow anon insert/update') then
    create policy "Allow anon insert/update" on public.movies for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'movies' and policyname = 'Allow authenticated full access') then
    create policy "Allow authenticated full access" on public.movies for all to authenticated using (true) with check (true);
  end if;

    if not exists (select 1 from pg_policies where tablename = 'homepage_config' and policyname = 'Allow anon insert/update config') then
    create policy "Allow anon insert/update config" on public.homepage_config for all to anon using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'homepage_config' and policyname = 'Allow authenticated full access config') then
    create policy "Allow authenticated full access config" on public.homepage_config for all to authenticated using (true) with check (true);
  end if;
end $$;
`;

  const handleFileChange = (e) => {
    setJsonFile(e.target.files[0]);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlScript);
    alert("SQL copied to clipboard! Paste it in Supabase SQL Editor.");
  };

  const handleUpload = async () => {
    if (!jsonFile) {
      setUploadStatus('Please select a JSON file first.');
      return;
    }

    setLoading(true);
    setUploadStatus('Reading file...');

    const reader = new FileReader();
    reader.onload = async (e) => {
      try {
        const text = e.target.result;
        const data = JSON.parse(text);
        const movies = data.movies || (Array.isArray(data) ? data : []);

        if (movies.length === 0) {
          setUploadStatus('Error: No movies found in JSON.');
          setLoading(false);
          return;
        }

        setUploadStatus(`Found ${movies.length} movies. Uploading to Supabase...`);

        // Data Transformation
        const formattedMovies = movies.map(m => ({
          id: m.id,
          title: m.title,
          year: m.year,
          rating: m.rating,
          category: m.category,
          description: m.description,
          "frontImage": m.frontImage,
          "backImage": m.backImage,
          certification: m.certification,
          duration: m.duration,
          "watchLink": m.watchLink,
          "top10": m.top10,
          "isNewRelease": m.isNewRelease,
          "isPopular": m.isPopular,
          director: m.director,
          writers: m.writers,
          cast: m.cast,
          awards: m.awards,
          language: m.language,
          country: m.country,
          "releaseDate": m.releaseDate,
          featured: m.featured
        }));

        const { error } = await supabase
          .from('movies')
          .upsert(formattedMovies, { onConflict: 'id', ignoreDuplicates: false });

        if (error) {
          throw error;
        }

        setUploadStatus(`Success! Uploaded/Updated ${movies.length} movies.`);
      } catch (err) {
        console.error("Upload error:", err);
        setUploadStatus(`Error: ${err.message}`);
      } finally {
        setLoading(false);
      }
    };
    reader.readAsText(jsonFile);
  };

  return (
    <div style={{ padding: '2rem', maxWidth: '800px', margin: '0 auto', minHeight: '80vh' }}>
      <h1 style={{ marginBottom: '2rem', color: '#03c76c' }}>Admin Dashboard Tool</h1>

      <div style={{
        background: 'white',
        padding: '2rem',
        borderRadius: '15px',
        boxShadow: '0 10px 30px rgba(0,0,0,0.1)',
        marginBottom: '2rem'
      }}>
        <h2 style={{ marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '10px', color: '#333' }}>
          <FaDatabase /> 1. Database Setup
        </h2>
        <p style={{ marginBottom: '1rem', color: '#666' }}>
          Copy the SQL below and run it in the <a href="https://supabase.com/dashboard/project/_/sql" target="_blank" rel="noreferrer" style={{ color: '#03c76c' }}>Supabase SQL Editor</a>.
        </p>

        <button
          onClick={() => setShowSql(!showSql)}
          style={{
            background: '#f8f9fa', border: '1px solid #ddd', padding: '0.5rem 1rem', borderRadius: '5px', cursor: 'pointer', marginBottom: '1rem'
          }}
        >
          {showSql ? 'Hide SQL Script' : 'Show SQL Script'}
        </button>

        {showSql && (
          <div style={{ position: 'relative' }}>
            <pre style={{
              background: '#1e1e1e',
              color: '#d4d4d4',
              padding: '1rem',
              borderRadius: '8px',
              overflowX: 'auto',
              fontSize: '0.9rem'
            }}>
              {sqlScript}
            </pre>
            <button
              onClick={copyToClipboard}
              style={{
                position: 'absolute',
                top: '10px',
                right: '10px',
                background: '#03c76c',
                color: 'white',
                border: 'none',
                padding: '0.3rem 0.8rem',
                borderRadius: '4px',
                cursor: 'pointer',
                fontSize: '0.8rem'
              }}
            >
              Copy
            </button>
          </div>
        )}
      </div>

      <div style={{
        background: 'white',
        padding: '2rem',
        borderRadius: '15px',
        boxShadow: '0 10px 30px rgba(0,0,0,0.1)'
      }}>
        <h2 style={{ marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <FaUpload /> 2. Upload Data
        </h2>

        <div style={{ marginBottom: '2rem' }}>
          <p style={{ marginBottom: '1rem', color: '#555' }}>
            Upload your <code>movies.json</code> file here to populate the Supabase database.
          </p>

          <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', flexWrap: 'wrap' }}>
            <input
              type="file"
              accept=".json"
              onChange={handleFileChange}
              style={{ padding: '0.5rem' }}
            />
            <button
              onClick={handleUpload}
              disabled={loading}
              style={{
                background: loading ? '#ccc' : 'linear-gradient(135deg, #03c76c, #d3f57f)',
                color: 'white',
                border: 'none',
                padding: '0.8rem 1.5rem',
                borderRadius: '50px',
                fontWeight: 'bold',
                cursor: loading ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem'
              }}
            >
              {loading ? 'Processing...' : <><FaUpload /> Upload to Database</>}
            </button>
          </div>
        </div>

        {uploadStatus && (
          <div style={{
            padding: '1rem',
            borderRadius: '8px',
            background: uploadStatus.includes('Error') ? '#ffebee' : '#e8f5e9',
            color: uploadStatus.includes('Error') ? '#c62828' : '#2e7d32',
            marginTop: '1rem',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem'
          }}>
            {uploadStatus.includes('Error') ? <FaExclamationTriangle /> : <FaCheck />}
            {uploadStatus}
          </div>
        )}
      </div>
    </div>
  );
};

export default DataImport;
